services:
  bioinformatics:
    build: .
    container_name: bioinformatics-env
    ports:
      - "8787:8787"  # RStudio Server
      - "8888:8888"  # Jupyter Lab
      - "8080:8080"  # VSCode Server
    volumes:
      - ./workspace:/workspace
      # Use named volumes for better permission handling
      - rstudio-home:/home/rstudio
      - rstudio-local:/home/rstudio/.local
      - rstudio-config:/home/rstudio/.config
      - rstudio-lib:/var/lib/rstudio-server
    environment:
      - PASSWORD=${RSTUDIO_PASSWORD:-rstudio}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-jupyter}
      - DISABLE_AUTH=${DISABLE_AUTH:-false}
      - USER=rstudio
      - USERID=1000
      - GROUPID=1000
    restart: unless-stopped
    stdin_open: true
    tty: true
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-45G}
        reservations:
          memory: ${MEMORY_RESERVATION:-16G}
    init: true

volumes:
  rstudio-home:
  rstudio-local:
  rstudio-config:
  rstudio-lib:
