services:
  bioinformatics:
    build: .
    container_name: bioinformatics-env
    ports:
      - "8787:8787"  # RStudio Server
      - "8888:8888"  # Jupyter Lab
      - "8080:8080"  # VSCode Server
    volumes:
      - ./workspace:/workspace
      - ./home:/home/rstudio  # Persist RStudio settings
    environment:
      - PASSWORD=${RSTUDIO_PASSWORD:-rstudio}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-}
      - DISABLE_AUTH=${DISABLE_AUTH:-true}
      - USER=rstudio
      - USERID=1000
      - GROUPID=1000
    restart: unless-stopped
    stdin_open: true
    tty: true
    # Increase shared memory size (helps with browser crashes)
    shm_size: '30gb'
    # Add resource limits
    deploy:
      resources:
        limits:
          memory: 40G
        reservations:
          memory: 20G